# Generated by Django 3.2.16 on 2022-11-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=15)),
                ('familiya', models.CharField(max_length=18)),
                ('yosh', models.IntegerField(default=16)),
            ],
        ),
    ]
